name: Analyze

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]
        language: [ 'javascript' ]
       
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node }}

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: cache node_modules
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Installling dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Eslint / Code linting
      run: npm run lint:check

    - name: Prettier / Code style
      run: npm run prettier:check

    - name: Build
      run: npm run generate

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
